import classNames from "classnames";
import type { Metadata } from "next";

import { Footer } from "@/app/components/Footer";
import { Header } from "@/app/components/Header";
import ThemeProviderContext from "@/app/context/ThemeProviderContext";

import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={styles.body}>
        <ThemeProviderContext>
          <section
            className={classNames(styles.container, {
              [styles.wideContainer!]: true,
            })}
          >
            <Header />
            {children}
            <Footer />
          </section>
        </ThemeProviderContext>
      </body>
    </html>
  );
}
